### ISSUE TITLE
Crash during accessing shared buffer

### ISSUE THREAD

**Issue by jhahn21** [domokit/mojo#587] opened 2015-12-10 03:40 UTC
When I pass a (duplicated) shared buffer handle from mojo to sysui and accessing the buffer, it crashes after some number of iterations. (on Android)

```
% mojo_debug device stack
Inferring the build directory path as /usr/local/google/home/jhahn/mojo/src/out/android_Debug
Inferring the Android NDK path as /usr/local/google/home/jhahn/mojo/src/third_party/android_tools/ndk
Reading native crash info from stdin
Reading symbols from ['/usr/local/google/home/jhahn/mojo/src/out/android_Debug']
signal 11 (SIGSEGV), code 1, fault addr 0xb1edf000 in tid 2302 (mojo_shell_chil)
pid: 2302, tid: 2302, name: mojo_shell_chil  >>> /data/user/0/org.chromium.mojo.shell/app_child/mojo_shell_child <<<
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0xb1edf000
     r0 00000000  r1 00000000  r2 ac57f059  r3 ac57eff9
     r4 b1edf000  r5 ac5d5821  r6 00000000  r7 ac57f059
     r8 ab57700d  r9 b089ba19  sl b6bc3c00  fp beb2fc24
     ip beab3d5c  sp beb2fabc  lr ac57f059  pc b0411cac

Stack Trace:
  RELADDR   FUNCTION  FILE:LINE
  0001bcac    <unknown>
  010c8057    <unknown>
```
[logcat.txt](https://github.com/domokit/mojo/files/57616/logcat.txt)

@jamesr

**Comment by jamesr** [comment] 2015-12-10 05:47
@qsr - what should Jungho do here to get a symbolized stack trace?

**Comment by ppiet** [comment] 2015-12-10 13:34
I'd suggest to try running under gdb, as described here https://github.com/domokit/mojo/blob/master/mojo/devtools/common/docs/mojo_debug.md#gdb . 

Please also ensure that you are running a locally built debug build.

If that doesn't help, can you describe repro steps so that we can investigate?

@emembrives

**Comment by jhahn21** [comment] 2015-12-10 18:09
I tried 'gdb attach', but I failed to that.
I gave --debugger to mojo_run and I ran mojo_debug gdb attach, but I got

```
...
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word".
/system/bin/sh: gdbserver: not found
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "mojo/devtools/common/android_gdb/session.py", line 281, in start
    self._rfc.connect()
  File "/usr/local/google/home/jhahn/mojo-test/src/mojo/devtools/common/android_gdb/remote_file_connection.py", line 28, in connect
    self._socket.connect((self._host, self._port))
  File "/usr/local/google/home/jhahn/mojo-test/src/third_party/android_tools/ndk/prebuilt/linux-x86_64/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 111] Connection refused
/tmp/tmpTz9tCx:3: Error in sourced command file:
Error while executing Python code.
```

My device is connected remotely from my ubiquity machine and I'm port-forwarding for remote adb.
Probably I missed some step for remote debugging.

BTW I grabbed the device stack again when it crashed this morning. The stack trace showed more useful info this time.

```
sing toolchain from :/usr/local/google/home/jhahn/mojo-test/src/third_party/android_tools/ndk/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-
signal 11 (SIGSEGV), code 1, fault addr 0xbe7f90a2 in tid 31908 (mojo_shell_chil)
pid: 31908, tid: 31908, name: mojo_shell_chil  >>> /data/user/0/org.chromium.mojo.shell/app_child/mojo_shell_child <<<
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0xbe7f90a2
     r0 f70f41c0  r1 f70f2080  r2 f6cf23f8  r3 be7f90a2
     r4 f4cd41c8  r5 f4cd41c0  r6 00000000  r7 aad81509
     r8 f6f91280  r9 ffdf8cc8  sl 00000000  fp ffdf947c
     ip ffff0000  sp ffdf85c8  lr f6aa3f73  pc f6aa3bd4

Stack Trace:
  RELADDR   FUNCTION                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             FILE:LINE
  0001bbd4  <unknown>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            /data/data/org.chromium.mojo.shell/app_home/.mojo_url_response_disk_cache/cache/04C459FA20E518B5DED1173A8F787F0A2BC9735015D23F6C834BDE2538915F6E/04C459FA20E518B5DED1173A8F787F0A2BC9735015D23F6C834BDE2538915F6E
  0001bf6f  <unknown>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            /data/data/org.chromium.mojo.shell/app_home/.mojo_url_response_disk_cache/cache/04C459FA20E518B5DED1173A8F787F0A2BC9735015D23F6C834BDE2538915F6E/04C459FA20E518B5DED1173A8F787F0A2BC9735015D23F6C834BDE2538915F6E
  0001accf  <unknown>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            /data/data/org.chromium.mojo.shell/app_home/.mojo_url_response_disk_cache/cache/04C459FA20E518B5DED1173A8F787F0A2BC9735015D23F6C834BDE2538915F6E/04C459FA20E518B5DED1173A8F787F0A2BC9735015D23F6C834BDE2538915F6E
  0003b85b  <unknown>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            /data/data/org.chromium.mojo.shell/app_home/.mojo_url_response_disk_cache/cache/04C459FA20E518B5DED1173A8F787F0A2BC9735015D23F6C834BDE2538915F6E/04C459FA20E518B5DED1173A8F787F0A2BC9735015D23F6C834BDE2538915F6E
  0004a415  gles2::CommandBufferClientImpl::MakeProgressAndUpdateState()                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         /usr/local/google/home/jhahn/mojo-test/src/out/android_Debug/../../mojo/gles2/command_buffer_client_impl.cc:325
  0004a4bb  gles2::CommandBufferClientImpl::WaitForGetOffsetInRange(int, int)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    /usr/local/google/home/jhahn/mojo-test/src/out/android_Debug/../../mojo/gles2/command_buffer_client_impl.cc:205
  0004c9f1  gpu::CommandBufferHelper::WaitForGetOffsetInRange(int, int)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          /usr/local/google/home/jhahn/mojo-test/src/out/android_Debug/../../gpu/command_buffer/client/cmd_buffer_helper.cc:144
  0004cbb3  gpu::CommandBufferHelper::Finish()                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   /usr/local/google/home/jhahn/mojo-test/src/out/android_Debug/../../gpu/command_buffer/client/cmd_buffer_helper.cc:197
  00053b1b  gpu::gles2::GLES2Implementation::FinishHelper()                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      /usr/local/google/home/jhahn/mojo-test/src/out/android_Debug/../../gpu/command_buffer/client/gles2_implementation.cc:1151
  00053b55  gpu::gles2::GLES2Implementation::Finish()                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            /usr/local/google/home/jhahn/mojo-test/src/out/android_Debug/../../gpu/command_buffer/client/gles2_implementation.cc:1132
  00078b8b  MojoGLES2glFinish                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    /usr/local/google/home/jhahn/mojo-test/src/out/android_Debug/../../mojo/public/platform/native/gles2/call_visitor_autogen.h:162 (discriminator 17)
  00047ccb  <unknown>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            /data/data/org.chromium.mojo.shell/app_home/.mojo_url_response_disk_cache/cache/04C459FA20E518B5DED1173A8F787F0A2BC9735015D23F6C834BDE2538915F6E/04C459FA20E518B5DED1173A8F787F0A2BC9735015D23F6C834BDE2538915F6E
  00047d79  <unknown>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            /data/data/org.chromium.mojo.shell/app_home/.mojo_url_response_disk_cache/cache/04C459FA20E518B5DED1173A8F787F0A2BC9735015D23F6C834BDE2538915F6E/04C459FA20E518B5DED1173A8F787F0A2BC9735015D23F6C834BDE2538915F6E
  0004e313  <unknown>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            /data/data/org.chromium.mojo.shell/app_home/.mojo_url_response_disk_cache/cache/04C459FA20E518B5DED1173A8F787F0A2BC9735015D23F6C834BDE2538915F6E/04C459FA20E518B5DED1173A8F787F0A2BC9735015D23F6C834BDE2538915F6E
  0004e36d  <unknown>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            /data/data/org.chromium.mojo.shell/app_home/.mojo_url_response_disk_cache/cache/04C459FA20E518B5DED1173A8F787F0A2BC9735015D23F6C834BDE2538915F6E/04C459FA20E518B5DED1173A8F787F0A2BC9735015D23F6C834BDE2538915F6E
  0001b113  <unknown>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            /data/data/org.chromium.mojo.shell/app_home/.mojo_url_response_disk_cache/cache/04C459FA20E518B5DED1173A8F787F0A2BC9735015D23F6C834BDE2538915F6E/04C459FA20E518B5DED1173A8F787F0A2BC9735015D23F6C834BDE2538915F6E
  0001b19d  <unknown>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            /data/data/org.chromium.mojo.shell/app_home/.mojo_url_response_disk_cache/cache/04C459FA20E518B5DED1173A8F787F0A2BC9735015D23F6C834BDE2538915F6E/04C459FA20E518B5DED1173A8F787F0A2BC9735015D23F6C834BDE2538915F6E
  00055839  <unknown>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            /data/data/org.chromium.mojo.shell/app_home/.mojo_url_response_disk_cache/cache/04C459FA20E518B5DED1173A8F787F0A2BC9735015D23F6C834BDE2538915F6E/04C459FA20E518B5DED1173A8F787F0A2BC9735015D23F6C834BDE2538915F6E
  00199291  <unknown>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            /data/data/org.chromium.mojo.shell/app_home/.mojo_url_response_disk_cache/cache/04C459FA20E518B5DED1173A8F787F0A2BC9735015D23F6C834BDE2538915F6E/04C459FA20E518B5DED1173A8F787F0A2BC9735015D23F6C834BDE2538915F6E
  0019a139  <unknown>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            /data/data/org.chromium.mojo.shell/app_home/.mojo_url_response_disk_cache/cache/04C459FA20E518B5DED1173A8F787F0A2BC9735015D23F6C834BDE2538915F6E/04C459FA20E518B5DED1173A8F787F0A2BC9735015D23F6C834BDE2538915F6E
  0019a25b  <unknown>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            /data/data/org.chromium.mojo.shell/app_home/.mojo_url_response_disk_cache/cache/04C459FA20E518B5DED1173A8F787F0A2BC9735015D23F6C834BDE2538915F6E/04C459FA20E518B5DED1173A8F787F0A2BC9735015D23F6C834BDE2538915F6E
  0019a4a9  <unknown>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            /data/data/org.chromium.mojo.shell/app_home/.mojo_url_response_disk_cache/cache/04C459FA20E518B5DED1173A8F787F0A2BC9735015D23F6C834BDE2538915F6E/04C459FA20E518B5DED1173A8F787F0A2BC9735015D23F6C834BDE2538915F6E
  0019a59f  <unknown>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            /data/data/org.chromium.mojo.shell/app_home/.mojo_url_response_disk_cache/cache/04C459FA20E518B5DED1173A8F787F0A2BC9735015D23F6C834BDE2538915F6E/04C459FA20E518B5DED1173A8F787F0A2BC9735015D23F6C834BDE2538915F6E
  000257dd  <unknown>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            /data/data/org.chromium.mojo.shell/app_home/.mojo_url_response_disk_cache/cache/04C459FA20E518B5DED1173A8F787F0A2BC9735015D23F6C834BDE2538915F6E/04C459FA20E518B5DED1173A8F787F0A2BC9735015D23F6C834BDE2538915F6E
  0002323d  <unknown>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            /data/data/org.chromium.mojo.shell/app_home/.mojo_url_response_disk_cache/cache/04C459FA20E518B5DED1173A8F787F0A2BC9735015D23F6C834BDE2538915F6E/04C459FA20E518B5DED1173A8F787F0A2BC9735015D23F6C834BDE2538915F6E
  00051c27  <unknown>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            /data/data/org.chromium.mojo.shell/app_home/.mojo_url_response_disk_cache/cache/04C459FA20E518B5DED1173A8F787F0A2BC9735015D23F6C834BDE2538915F6E/04C459FA20E518B5DED1173A8F787F0A2BC9735015D23F6C834BDE2538915F6E
  0001c01b  <unknown>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            /data/data/org.chromium.mojo.shell/app_home/.mojo_url_response_disk_cache/cache/04C459FA20E518B5DED1173A8F787F0A2BC9735015D23F6C834BDE2538915F6E/04C459FA20E518B5DED1173A8F787F0A2BC9735015D23F6C834BDE2538915F6E
  0003e2d5  shell::RunNativeApplication(void*, mojo::InterfaceRequest<mojo::Application>)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        /usr/local/google/home/jhahn/mojo-test/src/out/android_Debug/../../shell/native_application_support.cc:137
  0000c7d5  StartAppOnMainThread                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 /usr/local/google/home/jhahn/mojo-test/src/out/android_Debug/../../shell/child_main.cc:273 (discriminator 2)
  v------>  base::internal::RunnableAdapter<void (*)(base::FilePath const&, mojo::InterfaceRequest<mojo::Application>)>::Run(base::FilePath const&, mojo::InterfaceRequest<mojo::Application>)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   /usr/local/google/home/jhahn/mojo-test/src/out/android_Debug/../../base/bind_internal.h:157 (discriminator 2)
  v------>  base::internal::InvokeHelper<false, void, base::internal::RunnableAdapter<void (*)(base::FilePath const&, mojo::InterfaceRequest<mojo::Application>)>, base::internal::TypeList<base::FilePath const&, mojo::InterfaceRequest<mojo::Application> > >::MakeItSo(base::internal::RunnableAdapter<void (*)(base::FilePath const&, mojo::InterfaceRequest<mojo::Application>)>, base::FilePath const&, mojo::InterfaceRequest<mojo::Application>)                                                                                                                                                                                                                                                                                                                                                                                                                                        /usr/local/google/home/jhahn/mojo-test/src/out/android_Debug/../../base/bind_internal.h:293 (discriminator 2)
  0000c637  base::internal::Invoker<base::IndexSequence<0u, 1u>, base::internal::BindState<base::internal::RunnableAdapter<void (*)(base::FilePath const&, mojo::InterfaceRequest<mojo::Application>)>, void (base::FilePath const&, mojo::InterfaceRequest<mojo::Application>), base::internal::TypeList<base::FilePath, base::internal::PassedWrapper<mojo::InterfaceRequest<mojo::Application> > > >, base::internal::TypeList<base::internal::UnwrapTraits<base::FilePath>, base::internal::UnwrapTraits<base::internal::PassedWrapper<mojo::InterfaceRequest<mojo::Application> > > >, base::internal::InvokeHelper<false, void, base::internal::RunnableAdapter<void (*)(base::FilePath const&, mojo::InterfaceRequest<mojo::Application>)>, base::internal::TypeList<base::FilePath const&, mojo::InterfaceRequest<mojo::Application> > >, void ()>::Run(base::internal::BindStateBase*)  /usr/local/google/home/jhahn/mojo-test/src/out/android_Debug/../../base/bind_internal.h:346 (discriminator 2)
  v------>  base::Callback<void ()>::Run() const                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 /usr/local/google/home/jhahn/mojo-test/src/out/android_Debug/../../base/callback.h:396 (discriminator 1)
  0000c74d  Block                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                /usr/local/google/home/jhahn/mojo-test/src/out/android_Debug/../../shell/child_main.cc:78 (discriminator 1)
  0000b719  main                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 /usr/local/google/home/jhahn/mojo-test/src/out/android_Debug/../../shell/child_main.cc:325
  0001735d  __libc_init+44                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       /system/lib/libc.so
  0007db6c  _start                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               libgcc2.c:?
```

**Comment by jhahn21** [comment] 2015-12-10 18:13
Here is the logcat when it crashed in the previous run.
[logcat.txt](https://github.com/domokit/mojo/files/58486/logcat.txt)

**Comment by jhahn21** [comment] 2015-12-10 23:42
After I flashed the device with userdebug build, gdbserver could be found. But another error:

```
Type "apropos word" to search for commands related to "word".
Cannot attach to lwp 10428: Operation not permitted (1)
Exiting
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "mojo/devtools/common/android_gdb/session.py", line 281, in start
    self._rfc.connect()
  File "/usr/local/google/home/jhahn/mojo-test/src/mojo/devtools/common/android_gdb/remote_file_connection.py", line 31, in connect
    self._socket.connect((self._host, self._port))
  File "/usr/local/google/home/jhahn/mojo-test/src/third_party/android_tools/ndk/prebuilt/linux-x86_64/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 111] Connection refused
/tmp/tmpcfqIv6:3: Error in sourced command file:
```

**Comment by jamesr** [comment] 2015-12-11 00:45
Does running 'adb root' return successfully?

**Comment by jhahn21** [comment] 2015-12-11 00:49
I just tried that. Now I got another error.

```
Type "apropos word" to search for commands related to "word".
Attached; pid = 8931
Listening on port 9999
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "mojo/devtools/common/android_gdb/session.py", line 281, in start
    self._rfc.connect()
  File "/usr/local/google/home/jhahn/mojo-test/src/mojo/devtools/common/android_gdb/remote_file_connection.py", line 30, in connect
    self._socket.connect((self._host, self._port))
  File "/usr/local/google/home/jhahn/mojo-test/src/third_party/android_tools/ndk/prebuilt/linux-x86_64/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 111] Connection refused
/tmp/tmp9uJ2pM:3: Error in sourced command file:
Error while executing Python code.
(gdb) 
```

**Comment by qsr** [comment] 2015-12-11 08:49
@emembrives  and @ppiet  will know better that I do, but I think the tooling for gdb doesn't support remote execution.

**Comment by jhahn21** [comment] 2015-12-11 16:42
I could attach remotely by forwarding additional ports.

**Comment by jhahn21** [comment] 2015-12-12 00:47
Unfortunately I couldn't find anything with gdb.

It seems that the crash occurs in a child shell, but I couldn't attach to it or catch sigsegv with gdb.
I tried to run without --enable-multiprocess, but I couldn't use gdb with that since it hung.

I tried to add LOG() in Map() and Unmap() in platform/dart/mojo_natives.cc to see the mapped address, but I couldn't see that log.

**Comment by jhahn21** [comment] 2015-12-17 18:05
SIGSEGV occurs when accessing the mapped memory in Dart.

I simplified the code for testing like

```
var r = bufferHandle.map(0, length, MojoSharedBuffer.MAP_FLAG_NONE);
if (r !=  MojoResult.kOk) {
   // error...
}

Uint8List copy = new Uint8List(length);
copy[0] = bufferHandle.mapping.getUint8(0);  // <- SIGSEGV occurs here.

bufferHandle.unmap();
bufferHandle.close();
```

It also seems to be related to Dart VM memory.

SIGSEGV occurs after several iterations when length is large like 30000. 

But when I change ```copy```'s size like
```
Uint8List copy = new Uint8List(1000);
````
it didn't happen (I didn't change the shared data buffer size, which is about 10~30K.)

I guess there is some limitation on Dart VM memory size. In any case, map() always returns ok.

**Comment by jamesr** [comment] 2015-12-18 00:22
That's good info.  Can you produce a fully standalone repro using this information?  I suspect the VM's handling of external arrays of shared memory is not quite right and it'd be very useful to hand the VM engineers something isolated to poke at.

@zanderso @johnmccutchan @iposva-google

**Comment by zanderso** [comment] 2015-12-18 03:54
I suspect that the native wrapper MojoSharedBuffer_Unmap() at:

https://github.com/domokit/mojo/blob/master/mojo/public/platform/dart/mojo_natives.cc#L345

needs to explicitly delete the WeakPersistentHandle created above it by MojoSharedBuffer_Map() to prevent the finalizer from running. If the finalizer runs after unmap has been called, it could possibly be calling MojoUnmapBuffer() on an address that has already been unmapped.

It would be great to have a full repro to confirm and add a regression test, if possible.

**Comment by zanderso** [comment] 2015-12-18 17:08
I've managed to create a reproduction. The simplest solution would be to eliminate the finalizer. The downside of this approach would be that the mappings for a leaked buffer handle wouldn't be unmapped.

@jamesr, when a buffer handle is closed, are the mappings cleaned up? If so, then I think the Dart content handler's tracking of unclosed handles would be sufficient here.

**Comment by zanderso** [comment] 2015-12-18 18:24
Spoke offline with @viettrungluu-cr and @iposva-google.
1. Closing a shared buffer handle does not clean up the mappings.
2. Multiple calls to Map on a shared buffer handle should give different addresses, even if the offset is the same.
3. We don't want to have dangling pointers in the Dart heap.

Given the above, it seems like the right thing to do is retain a finalizer, but hook it up to the underlying ByteData for each mapping instead of Dart's wrapper class, and remove explicit calls to unmap from Dart code. The finalizers won't clobber an address that's still in use since we'll get different addresses back from each call to Map, and we won't have dangling pointers in the Dart heap.

**Closed** 2015-12-18 20:36 UTC
