### ISSUE TITLE
SkyDemo.apk crashing

### ISSUE THREAD

**Issue by eseidelGoogle** [domokit/mojo#147] opened 2015-05-06 18:01 UTC
We've seen 22 reports of this crash from SkyDemo.apk.

Looks like it's this assert:
  CHECK(size == 0 || (!!pointer && internal::IsAligned<alignment>(pointer)));
@viettrungluu-cr 

I'm not particularly worried about this crash, so much as the potential for us to find this bug in mojo and fix it. :)

pid: 30787, tid: 30787, name: omokit.sky.demo >>> org.domokit.sky.demo <<<
signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
r0 00000000 r1 00007843 r2 00000006 r3 00000000
r4 00000006 r5 00000016 r6 00007843 r7 0000010c
r8 beef4ae4 r9 00000000 sl 652a5e70 fp 652a7210
ip beef4698 sp beef45f8 lr 4005d1b5 pc 4006c160

Stack Trace:
  RELADDR   FUNCTION                                                                                                                                                                                FILE:LINE
  00022160  tgkill+12                                                                                                                                                                               /system/lib/libc.so
  000131b1  pthread_kill+48                                                                                                                                                                         /system/lib/libc.so
  000133c5  raise+10                                                                                                                                                                                /system/lib/libc.so
  000120fb  <unknown>                                                                                                                                                                               /system/lib/libc.so
  00021a14  abort+4                                                                                                                                                                                 /system/lib/libc.so
  v------>  DebugBreak                                                                                                                                                                              /src/mojo/src/out/android_Release/../../base/debug/debugger_posix.cc:217
  001da389  base::debug::BreakDebugger()                                                                                                                                                            /src/mojo/src/out/android_Release/../../base/debug/debugger_posix.cc:241
  00095f41  logging::LogMessage::~LogMessage()                                                                                                                                                      /src/mojo/src/out/android_Release/../../base/logging.cc:639
  000af0ff  void mojo::system::internal::CheckUserPointerWithSize<8u>(void const*, unsigned int)                                                                                                    /src/mojo/src/out/android_Release/../../mojo/edk/system/memory.cc:63 (discriminator 15)
  v------>  mojo::system::UserOptionsReader<MojoCreateMessagePipeOptions>::GetSizeForReader(mojo::system::UserPointer<MojoCreateMessagePipeOptions const>)                                          /src/mojo/src/out/android_Release/../../mojo/edk/system/options_validation.h:75
  v------>  _ZN4mojo6system17UserOptionsReaderI28MojoCreateMessagePipeOptionsEC4ENS0_11UserPointerIKS2_EE                                                                                           /src/mojo/src/out/android_Release/../../mojo/edk/system/options_validation.h:38
  000afe19  mojo::system::MessagePipeDispatcher::ValidateCreateOptions(mojo::system::UserPointer<MojoCreateMessagePipeOptions const>, MojoCreateMessagePipeOptions*)                                /src/mojo/src/out/android_Release/../../mojo/edk/system/message_pipe_dispatcher.cc:44
  000abab1  mojo::system::Core::CreateMessagePipe(mojo::system::UserPointer<MojoCreateMessagePipeOptions const>, mojo::system::UserPointer<unsigned int>, mojo::system::UserPointer<unsigned int>)  /src/mojo/src/out/android_Release/../../mojo/edk/system/core.cc:202
  0021c6e9  MojoCreateMessagePipe                                                                                                                                                                   /src/mojo/src/out/android_Release/../../mojo/edk/embedder/entrypoints.cc:49 (discriminator 3)
  v------>  CreateMessagePipe                                                                                                                                                                       /src/mojo/src/out/android_Release/../../mojo/android/system/core_impl.cc:106
  000a76db  Java_org_chromium_mojo_system_impl_CoreImpl_nativeCreateMessagePipe                                                                                                                     /src/mojo/src/out/android_Release/gen/mojo/android/system_java_jni_headers/mojo/jni/CoreImpl_jni.h:61
  000ac7a0  <unknown>                                                                                                                                                                               /data/dalvik-cache/data@app@org.domokit.sky.demo-1.apk@classes.dex

**Comment by jamesr** [comment] 2015-05-06 18:09
https://github.com/domokit/mojo/blob/master/mojo/android/system/src/org/chromium/mojo/system/impl/CoreImpl.java#L142 is allocating an options struct in the java heap and passing it in through JNI.  However, the buffer is not 8-byte aligned as CreateMessagePipe requires.  I also hit this in Go.  It's tricky to allocate memory with specific alignment requirements in various languages, but I think that this needs to be fixed on the Java side

@qsr

**Comment by jamesr** [comment] 2015-05-06 18:11
I don't see any promises made about alignment in http://docs.oracle.com/javase/7/docs/api/java/nio/ByteBuffer.html

**Comment by eseidelGoogle** [comment] 2015-05-06 18:26
I've only seen reports of this crash on Android 4.4.

**Comment by jamesr** [comment] 2015-05-06 18:30
It's possible that Dalvik on KitKat returns memory with <8 byte alignment whereas Art on Lollipop returns aligned memory.  In either case, relying on undocumented alignment is probably dodgy and for APIs that require 16 byte alignment even more so.

**Comment by qsr** [comment] 2015-05-07 09:11
Dalcik is fine, the issue is with some old version of Art that have been fixed since then ( https://android.googlesource.com/platform/libcore/+/a20d8a3%5E!/ ).

The 8 bytes alignment is undocumented, but used by everyone (see http://psy-lob-saw.blogspot.fr/2013/01/direct-memory-alignment-in-java.html), because otherwise direct bytebuffer are just not useful at all.

I don't think we should solve this, as this will be a big performance hit, as there is no Java API that allows us to find out what is the alignment of a bytebuffer, so it won't allow us to write struct in java without doing jni calls.

**Comment by qsr** [comment] 2015-05-07 09:14
James -> which API does require 16 bytes alignment? We do not require this at this point anywhere in mojo. We only require 8.

**Comment by jamesr** [comment] 2015-05-07 17:40
If we can't run on some versions of Art can we detect that and fail in a more graceful way?

**Closed** 2015-05-22 12:45 UTC
