### ISSUE TITLE
generate.dart should work regardless of sdk path

### ISSUE THREAD

**Issue by tonygentilcore** [domokit/mojo#330] opened 2015-07-20 22:08 UTC
I have a private repo which is consuming the `mojo_sdk` repo. It needs to run `generate.dart` in order to generate mojom bindings. Everything works great if I pull the sdk into `third_party/mojo_sdk/mojo/public`. However, I'd like to be able to pull it into `third_party/mojo_sdk` instead.

When I try that, it breaks because of this hardcoded path in `generate.dart`:
```dart
    final script = path.join(data.mojoSdk.path,
        'mojo', 'public', 'tools', 'bindings', 'mojom_bindings_generator.py');
```

/cc @johnmccutchan @zanderso

**Comment by johnmccutchan** [comment] 2015-07-20 22:18
We should poll a MOJO_SDK environment variable.

**Comment by zanderso** [comment] 2015-07-20 22:47
I just landed https://codereview.chromium.org/1210253006 which expects the actual sdk path, instead of the path in the Mojo tree, and drops "'mojo', 'public'" from that path. We already poll MOJO_SDK if --mojo-sdk (-m) isn't on the command line. It was just expecting the wrong thing before my change.

**Comment by zanderso** [comment] 2015-07-21 14:57
Oh, wait. I see what I was doing now. The problem is that the import paths of e.g. //mojo/public/interfaces/application/application.mojom include the "mojo/public" part. If you don't have the mojo_sdk repo checked out under 'mojo/public' then third party mojoms can't import SDK mojoms since it won't be possible to resolve those import paths. (The generate script does the right thing otherwise.)

I wonder if e.g. C++ #includes in generated code will work when the SDK isn't checked out under '.../mojo/public' somewhere.

**Comment by johnmccutchan** [comment] 2015-07-30 17:19
@tonygentilcore FYI- I've just landed a set of changes that removes the need to run the generate.dart script.

**Closed** 2015-07-31 18:49 UTC
