### ISSUE TITLE
Find a better way to do the hashCode functions

### ISSUE THREAD

**Issue by Hixie** [domokit/mojo#193] opened 2015-06-04 00:22 UTC
Rect, Point, Size, BorderSide, Border, EdgeDims, and BoxConstraints all have the same logic to do their hash codes.

@eseidelGoogle

**Comment by sethladd** [comment] 2015-06-04 02:42
Quiver has hashCode builders: http://www.dartdocs.org/documentation/quiver/0.21.4/index.html#quiver/quiver-core

**Comment by abarth** [comment] 2015-06-13 17:08
Duplicate of #236

**Closed by abarth** 2015-06-13 17:08 UTC
Labels: enhancement, framework, sky
