### ISSUE TITLE
Mojom compiler: propagate the comments

### ISSUE THREAD

**Issue by floitschG** [domokit/mojo#683] opened 2016-02-21 00:33 UTC
The mojom-compiler frontend should make it possible for the backends to generate documentation.
As a good start it would already be nice if the documentation could be copied verbatim, but to be really platform independent, it should be the front-end that parses the documentation. For example, the `|x|` convention should be recognized by the frontend and not by each generator.
This is important, since names change, and `|x|` could potentially have a different name in the output.

To provide really good documentation for all backends, one might need to change the current conventions, since they don't contain enough information for all languages. For example, dartdoc uses markdown style, and needs to know when a paragraph starts. The current mojom documentation generally does not add a blank line between paragraphs.
Also, one should have two kinds of comments: the ones that are dev-comments in the mojom files, and the ones that are part of the specification. Dart solves this by having "///" for dartdocs and "//" for devs.

**Comment by krisgiesing** [comment] 2016-02-21 03:16
Dupe of https://github.com/domokit/mojo/issues/624?

**Comment by viettrungluu-cr** [comment] 2016-02-22 05:25
Indeed, dupe of #624.

**Closed by viettrungluu-cr** 2016-02-22 05:25 UTC
