### ISSUE TITLE
mojom compiler doesn't error out if a mojom file is missing a service name

### ISSUE THREAD

**Issue by apwilson** [domokit/mojo#724] opened 2016-03-22 00:16 UTC
Example mojom file.

```
//[ServiceName="foo::bar"]
interface Foo {
  Bar();
}
```

If you try to connect to a mojo app that provides the Foo service without specifying the ServiceName you get this exception.

```
16:59:46.291: Error encountered while encoding field interfaceName of struct _ServiceProviderConnectToServiceParams: Cannot encode a null pointer for a non-nullable type
16:59:46.295: Stack trace:
16:59:46.296: #0      Encoder.encodeNullPointer (packages/mojo/src/codec.dart:281)
16:59:46.297: #1      Encoder.encodeString (packages/mojo/src/codec.dart:514)
16:59:46.299: #2      _ServiceProviderConnectToServiceParams.encode (packages/mojo/mojo/service_provider.mojom.dart:69)
16:59:46.300: #3      Struct.serializeWithHeader (packages/mojo/src/struct.dart:23)
16:59:46.302: #4      Proxy.sendMessage (packages/mojo/src/proxy.dart:91)
16:59:46.304: #5      _ServiceProviderProxyCalls.connectToService (packages/mojo/mojo/service_provider.mojom.dart:161)
16:59:46.306: #6      ApplicationConnection.requestService (packages/mojo/src/application_connection.dart:96)
```

The mojom compiler doesn't error or or complain in any way but the resulting mojom.dart is unusable due to the above exception.

**Comment by viettrungluu-cr** [comment] 2016-03-22 00:51
This is not a bug. Service names are strictly optional (and not necessarily canonical), and there are many ways of using interfaces that don't have service names.

Whether the Dart bindings can be made to detect such problems statically (at "build" time) rather than at runtime is a separate issue. (E.g., if you tried to do this with C++, without manually specifying a service name, you'd get a compile failure.)

I assume that you may also explicitly give a service name (as I said, service names need not be declared, nor are they necessarily canonical/unique) to `connectToService()`, but I don't know enough about the Dart bindings to say for sure.

**Comment by pylaligand** [comment] 2016-03-22 18:11
Should this issue remain open and be focused on Dart bindings?

**Comment by viettrungluu-cr** [comment] 2016-03-22 18:14
Hmmm, maybe? I'm not sure what can be done. /cc @johnmccutchan @zanderso

**Comment by zanderso** [comment] 2016-03-22 18:30
`ApplicationConnection.requestService()` takes an optional positional string argument for the service name for the situation where there is no `[ServiceName=...]` annotation on the interface. You have to pass whatever name the implementation is providing the service under.

**Comment by zanderso** [comment] 2016-03-22 20:59
I've landed a change to hopefully improve the way this fails. I'll leave this open in case there are any more suggestions for how to improve things here.

**Comment by pylaligand** [comment] 2016-03-22 21:28
I believe that would be https://codereview.chromium.org/1819193003/. Thanks! We'll give it a shot.

**Closed** 2016-03-31 22:10 UTC
