### ISSUE TITLE
Reduce numebr of compositor logs or change log level

### ISSUE THREAD

**Issue by aghassemi** [domokit/mojo#738] opened 2016-04-01 16:42 UTC
I am seeing a lot of "Compositor missed snapshot deadline" in my console. Can the level or frequency be changed? As a user of mojo, I can't do anything to fix these warnings anyway so maybe they should be logged as info?

(I am running a flutter app in mojo shell)

@j9brown

**Comment by tonygentilcore** [comment] 2016-04-01 16:45
Dupe of #721

**Closed by tonygentilcore** 2016-04-01 16:45 UTC
